### ISSUE TITLE
Key Remapping crashes helix v0.5.0

### ISSUE THREAD

**Issue by PhilipK** [helix-editor/helix#1289]
### Reproduction steps

1. Copy the key remapping found here https://docs.helix-editor.com/remapping.html#key-remapping 
2. Add it to ~/.config/helix/config.toml
3. Run helix

Helix crashes with the following message:
Error: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 11 column 1

### Environment

- Platform:  Linux
- Helix version: 0.5.0

**Comment by PhilipK** [comment]
It seems this problem happens any time

**Comment by PhilipK** [comment]
This seems to have been solved in helix v0.5.0-257-g02fc52f when i build from master key remapping is possible

**Comment by sudormrfbin** [comment]
The docs are built from master and not the latest tagged release, hence the error.

**Comment by PhilipK** [comment]
The only difference between 
https://github.com/helix-editor/helix/blob/v0.5.0/book/src/remapping.md

and 

https://github.com/helix-editor/helix/blob/master/book/src/remapping.md

Is the added ctrl+s to save.
If i use the configuration from 0.5.0 the problem is still there.

**Comment by sudormrfbin** [comment]
I think you missed `"ret" = ["open_below", "normal_mode"]` which allows executing multiple commands, added after 0.5.

**Comment by PhilipK** [comment]
Still a problem on 0.5.0.
Here is some more information.
Here is what i did on an (almost) clean install of Arch Linux

1. Use `yay -S helix` to download helix-0.5.0-1
2. run `helix` and it starts no problem
3. Verify that helix is version 0.5.0 with -V argument
4. create a `config.toml` at `~/.config/helix/config.toml`
5. Write the following to `config.toml`
```toml
[keys.normal]
C-s = ":w"
"ret" = ["open_below", "normal_mode"]
```
6. Run `helix` again, and get the following error
```
Error: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 2 column 1
```
7. Edit the `config.toml`to 
```toml
[keys.normal]
"ret" = ["open_below", "normal_mode"]
```
8. Run `helix` again, and get the same error

**Comment by archseer** [comment]
Yeah, `"ret" = ["open_below", "normal_mode"]` won't work on 0.5.0 but it will work on the latest master since this feature was implemented after 0.5.0 was released.

**Comment by PhilipK** [comment]
This works:
```toml
[keys.normal]
a = "move_char_left"
```
so does this:
```toml
[keys.normal]
C-s = "move_char_left"
```

but this:
```toml
[keys.normal]
s = ":w"
```
and this:
```toml
[keys.normal]
s = ":write"
```toml
and this:
```toml
[keys.normal]
s = ":q"
```
Does not work. It seems to be related to keymapping a command

**Comment by archseer** [comment]
Yes, that's another feature that landed after 0.5. Mapping sequences of commands and and `:commands` is only possible on master until a new release comes out.
