### ISSUE TITLE
Metals integration is broken using version 0.11.8

### ISSUE THREAD

**Issue by voidcontext** [helix-editor/helix#3823]
### Summary

Scala Metals fails to start when a scala file from an sbt project is opened. Metals in producing the following error message:

```
ERROR Unexpected error initializing serverjava.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$syncUserconfiguration$6(MetalsLanguageServer.scala
```

It seems like the error is somehow related to the user config. Reverting back to 0.11.7  makes it work again (using the same helix version).

### Reproduction Steps

 

I tried this:

1. `hx path/to/some/scala.file`

I expected this to happen:

LSP Server to start and get lsp functionality.

Instead, this happened:

LSP Server didn't start, there isn't code completation, navigation, etc

### Helix log

N/A

### Platform

macOS

### Terminal Emulator

Kitty

### Helix Version

helix 22.08.1 (03612174ee4cef23217b5adf415ced4a851b4a44)

**Comment by archseer** [comment]
Can you reproduce with `hx -v` and share the logfile? We want to see what exactly we're sending to the LSP

**Comment by voidcontext** [comment]
Ahh, sorry forgot that we can get extra logs with `-v`, so here they are:

```
2022-09-13T09:55:37.019 helix_view::clipboard [INFO] Using pbcopy+pbpaste to interact with the system clipboard
2022-09-13T09:55:41.210 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false},"workspaceFolders":true}},"processId":62656,"rootPath":"/Users/gaborpihaj/workspace/personal/ghyll","rootUri":"file:///Users/gaborpihaj/workspace/personal/ghyll","workspaceFolders":[{"name":"ghyll","uri":"file:///Users/gaborpihaj/workspace/personal/ghyll"}]},"id":0}
2022-09-13T09:55:43.039 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:43 INFO  logging to file /Users/gaborpihaj/workspace/personal/ghyll/.metals/metals.log"}}
2022-09-13T09:55:43.040 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:43 INFO  logging to file /Users/gaborpihaj/workspace/personal/ghyll/.metals/metals.log" }
2022-09-13T09:55:43.047 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:43 INFO  Started: Metals version 0.11.8+92-cfb33b0b-SNAPSHOT in workspace \u0027/Users/gaborpihaj/workspace/personal/ghyll\u0027 ."}}
2022-09-13T09:55:43.047 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:43 INFO  Started: Metals version 0.11.8+92-cfb33b0b-SNAPSHOT in workspace '/Users/gaborpihaj/workspace/personal/ghyll' ." }
2022-09-13T09:55:43.978 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:43 INFO  Flyway Community Edition 9.3.0 by Redgate"}}
2022-09-13T09:55:43.978 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:43 INFO  Flyway Community Edition 9.3.0 by Redgate" }
2022-09-13T09:55:43.978 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:43 INFO  See what\u0027s new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.3.0"}}
2022-09-13T09:55:43.978 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:43 INFO  "}}
2022-09-13T09:55:43.979 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:43 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.3.0" }
2022-09-13T09:55:43.979 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:43 INFO  " }
2022-09-13T09:55:44.410 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 INFO  Database: jdbc:h2:file:/Users/gaborpihaj/workspace/personal/ghyll/.metals/metals (H2 2.1)"}}
2022-09-13T09:55:44.410 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 INFO  Database: jdbc:h2:file:/Users/gaborpihaj/workspace/personal/ghyll/.metals/metals (H2 2.1)" }
2022-09-13T09:55:44.489 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 INFO  Successfully validated 4 migrations (execution time 00:00.031s)"}}
2022-09-13T09:55:44.489 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 INFO  Successfully validated 4 migrations (execution time 00:00.031s)" }
2022-09-13T09:55:44.509 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 INFO  Current version of schema \"PUBLIC\": 4"}}
2022-09-13T09:55:44.509 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 INFO  Current version of schema \"PUBLIC\": 4" }
2022-09-13T09:55:44.511 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 INFO  Schema \"PUBLIC\" is up to date. No migration necessary."}}
2022-09-13T09:55:44.511 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 INFO  Schema \"PUBLIC\" is up to date. No migration necessary." }
2022-09-13T09:55:44.773 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 INFO  time: initialize in 1.76s"}}
2022-09-13T09:55:44.773 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 INFO  time: initialize in 1.76s" }
2022-09-13T09:55:44.793 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1,"save":{"includeText":true}},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","*"]},"signatureHelpProvider":{"triggerCharacters":["(","[",","]},"definitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","source.organizeImports"]},"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":["\""]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["analyze-stacktrace","bsp-switch","build-connect","compile-cancel","compile-cascade","compile-clean","convert-to-named-arguments","copy-worksheet-output","discover-tests","extract-member-definition","generate-bsp-config","goto-position","goto-super-method","goto","build-import","insert-inferred-type","new-scala-file","new-java-file","new-scala-project","presentation-compiler-restart","reset-choice","reset-notifications","build-restart","doctor-run","scalafix-run","file-decode","build-disconnect","list-build-targets","sources-scan","ammonite-start","debug-adapter-start","ammonite-stop","super-method-hierarchy","scala-cli-start","scala-cli-stop"]},"selectionRangeProvider":true,"experimental":{"rangeHoverProvider":true}},"serverInfo":{"name":"Metals","version":"0.11.8+92-cfb33b0b-SNAPSHOT"}}}
2022-09-13T09:55:44.793 helix_lsp::transport [INFO] <- {"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","source.organizeImports"]},"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","*"]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":["\""]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["analyze-stacktrace","bsp-switch","build-connect","compile-cancel","compile-cascade","compile-clean","convert-to-named-arguments","copy-worksheet-output","discover-tests","extract-member-definition","generate-bsp-config","goto-position","goto-super-method","goto","build-import","insert-inferred-type","new-scala-file","new-java-file","new-scala-project","presentation-compiler-restart","reset-choice","reset-notifications","build-restart","doctor-run","scalafix-run","file-decode","build-disconnect","list-build-targets","sources-scan","ammonite-start","debug-adapter-start","ammonite-stop","super-method-hierarchy","scala-cli-start","scala-cli-stop"]},"experimental":{"rangeHoverProvider":true},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(","[",","]},"textDocumentSync":{"change":1,"openClose":true,"save":{"includeText":true}},"workspaceSymbolProvider":true},"serverInfo":{"name":"Metals","version":"0.11.8+92-cfb33b0b-SNAPSHOT"}}
2022-09-13T09:55:44.793 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2022-09-13T09:55:44.793 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"scala","text":"package benchmark\n\nimport java.io.FileInputStream\nimport java.nio.charset.StandardCharsets\nimport java.nio.file.{Files, Paths}\nimport java.time.LocalDate\n\nimport scala.io.Source\nimport scala.math.Ordering.Implicits._\n\nimport benchmark.CliCommand._\nimport benchmark.Data.{DataSet, Item, PricePoint}\nimport cats.effect.{ExitCode, IO}\nimport cats.instances.either._\nimport cats.instances.list._\nimport cats.syntax.apply._\nimport cats.syntax.flatMap._\nimport cats.syntax.traverse._\nimport com.monovore.decline.Opts\nimport com.monovore.decline.effect.CommandIOApp\nimport ghyll._\nimport ghyll.syntax._\nimport io.circe.parser.{decode => circeDecode}\n\nobject Main\n    extends CommandIOApp(\n      name = \"benchmark\",\n      header = \"Benchmarking tools for Ghyll\"\n    ) {\n\n  val sampleFile = Paths.get(\"benchmark/generated.json\")\n  val mb = 1024 * 1024\n  val javaRuntime = Runtime.getRuntime\n\n  def findLatestPrice(prices: List[PricePoint]): BigDecimal =\n    prices\n      .foldLeft(LocalDate.of(1000, 1, 1) -> BigDecimal.valueOf(0)) { (acc, p) =>\n        if (acc._1 <= p.date) p.date -> p.price\n        else acc\n      }\n      ._2\n\n  def totalPrice(dataset: DataSet) =\n    dataset.values.foldLeft(BigDecimal.valueOf(0))((sum, item) => sum + findLatestPrice(item.prices))\n\n  def memoryUsage(): IO[Long] =\n    IO.delay((javaRuntime.totalMemory() - javaRuntime.freeMemory()) / mb)\n\n  def printMemoryUsage(m: Long): IO[Unit] =\n    IO.delay(println(s\"Current memory usage: ${m}\"))\n\n  def repeat[A](fa: IO[A], times: Int): IO[List[A]] =\n    List.fill(times)(fa).traverse(identity)\n\n  def printMemoryStats(values: List[Long]): IO[Unit] =\n    IO.delay(println(\"MemoryStats\")) >>\n      IO.delay(println(s\"Average: ${values.sum / values.length}\")) >>\n      IO.delay(println(s\"Max: ${values.max}\"))\n\n  def main: Opts[IO[ExitCode]] =\n    (generateSampleJson orElse [CliCommand] benchmarkCirce orElse [CliCommand] benchmarkGhyll).map {\n      case GenerateSampleJson     =>\n        Data\n          .generate[IO]\n          .flatMap(_.asJsonString[IO])\n          .flatMap(json => IO.delay(Files.write(sampleFile, json.getBytes(StandardCharsets.UTF_8))))\n          .as(ExitCode.Success)\n      case BenchmarkCirce(rounds) =>\n        (IO.delay(println(\"parse using circe\")) >>\n          repeat({\n            import io.circe.generic.auto._\n            for {\n              result       <- IO.delay(circeDecode[DataSet](Source.fromFile(sampleFile.toUri()).mkString))\n              errorOrTotal <- IO.delay(result.map(totalPrice))\n              _            <- IO.delay(println(errorOrTotal))\n              mem          <- memoryUsage()\n              _            <- printMemoryUsage(mem)\n            } yield mem\n          },\n            rounds\n          ) >>= printMemoryStats).as(ExitCode.Success)\n\n      case BenchmarkGhyll(rounds) =>\n        (IO.delay(println(\"parse using ghyll\")) >>\n          (repeat(\n            for {\n              inputStream                               <- IO.delay(new FileInputStream(sampleFile.toFile()))\n              errorOrTotal                              <-\n                decodeKeyValues[IO, Item](inputStream)\n                  .use(\n                    _.map(_.map(kv => findLatestPrice(kv._2.prices))).compile\n                      .fold[Either[ghyll.StreamingDecoderError, BigDecimal]](\n                        Right(BigDecimal.valueOf(0))\n                      )((sum, t) => (sum, t).mapN(_ + _))\n                  )\n              _                                         <- IO.delay(println(errorOrTotal))\n              mem                                       <- memoryUsage()\n              _                                         <- printMemoryUsage(mem)\n            } yield mem,\n            rounds\n          ) >>= printMemoryStats)).as(ExitCode.Success)\n    }\n\n}\n","uri":"file:///Users/gaborpihaj/workspace/personal/ghyll/benchmark/src/main/scala/benchmark/Main.scala","version":0}}}
2022-09-13T09:55:44.797 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"1","method":"workspace/configuration","params":{"items":[{"section":"metals"}]}}
2022-09-13T09:55:44.798 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":[null],"id":"1"}
2022-09-13T09:55:44.822 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"2022.09.13 09:55:44 ERROR Unexpected error initializing serverjava.lang.IllegalStateException: Not a JSON Object: null\n\tat com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)\n\tat scala.meta.internal.metals.MetalsLanguageServer.$anonfun$syncUserconfiguration$6(MetalsLanguageServer.scala:2726)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.lang.Thread.run(Thread.java:833)\n"}}
2022-09-13T09:55:44.822 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "2022.09.13 09:55:44 ERROR Unexpected error initializing serverjava.lang.IllegalStateException: Not a JSON Object: null\n\tat com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)\n\tat scala.meta.internal.metals.MetalsLanguageServer.$anonfun$syncUserconfiguration$6(MetalsLanguageServer.scala:2726)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.lang.Thread.run(Thread.java:833)\n" }

```

**Comment by julianbieber** [comment]
As a workaround you can specify a config for the lsp in the languaguages.toml. 
Example:
```
[[language]]
name = "scala"
scope = "source.scala"
roots = ["build.sbt", "pom.xml"]
file-types = ["scala", "sbt"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "metals" }
config = {metals.ammoniteJvmProperties = ["-Xmx1G"]}
```

**Comment by voidcontext** [comment]
> As a workaround you can specify a config for the lsp in the languaguages.toml. Example:
> 
> ```
> [[language]]
> name = "scala"
> scope = "source.scala"
> roots = ["build.sbt", "pom.xml"]
> file-types = ["scala", "sbt"]
> comment-token = "//"
> indent = { tab-width = 2, unit = "  " }
> language-server = { command = "metals" }
> config = {metals.ammoniteJvmProperties = ["-Xmx1G"]}
> ```

@julianbieber This workaround seems to be working, thanks!

**Comment by ckipp01** [comment]
Just a heads up, we've fixed this in Metals. You can test with the latest snapshot to see this working `0.11.9+128-92db24b7-SNAPSHOT`.

**Comment by mabasic** [comment]
I have tried the latest version of Helix and using metals 0.11.9 and it still did not work  without adding this line:

```
config = {metals.ammoniteJvmProperties = ["-Xmx1G"]}
```

**Comment by ckipp01** [comment]
The fix is contained in https://github.com/scalameta/metals/pull/4588, which isn't in a stable release yet. We'll be releasing `0.11.10` _hopefully_ this week, and that version will contain this fix.

**Comment by mabasic** [comment]
Running Helix 23.05 and metals 0.11.12 and I still have this issue, but when I add:

```
[[language]]
name = "scala"
config = {metals.ammoniteJvmProperties = ["-Xmx1G"]}
```

to `.helix/languages.toml` it works.

**Comment by teenjuna** [comment]
@asilvam133 thanks for this advice. I was using metals from Homebrew, which is also 1.0, but for some reason it just didn't work, even with all the config options provided in comments above. Your solution works though!

**Comment by tobibrunner** [comment]
my lsp won't start when i am inside a .sc file

i installed scala from aur and metals using coursier

hx --health output:

Configured language server: metals
Binary for language server: /home/user/.local/share/coursier/bin/metals
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✓

logs: 
2023-10-07T18:58:18.530 helix_lsp::transport [ERROR] <- InternalError: Internal error.
2023-10-07T18:58:18.530 helix_lsp [ERROR] failed to initialize language server: protocol error: InternalError: Internal error.


anyone can help me?
