### ISSUE TITLE
Fail to use system clipboard

### ISSUE THREAD

**Issue by Luv-Ray** [helix-editor/helix#8713]
### Summary

If I copy something from outside and paste into helix, it works normally.

If I copy something **in helix** into clipboard `(<space>Y)`, the copy will sucess (I can use copied text outside), but I **can't paste** what I have copied from clipboard.

> Clipboard provider: xclip
System clipboard provider: xclip

### Reproduction Steps

 

I tried this:

1. `hx`, edit a text
2. use `<space>Y` copy something into clipboard
3. `i` into insert mode
4. use `ctrl + shift + v`, and can't paste what I have copied

### Helix log

Noting gets logged when i run these commands.

### Platform

Arch Linux

### Terminal Emulator

Konsole

### Installation Method

Pacman

### Helix Version

helix 23.10

**Comment by woojiq** [comment]
In my case I need to paste in the insert mode with `ctrl-v` instead of `ctrl-shift-v` (I'm using wezterm). Try pasting the selection normally with `<space>p`, does it work?

**Comment by Luv-Ray** [comment]
> In my case I need to paste in the insert mode with `ctrl-v` instead of `ctrl-shift-v` (I'm using wezterm). 

I can use `ctrl-shift-v` to paste things from outside, and `ctrl-v` do not work.

>Try pasting selected in the normal mode with `<space>p`, does it work?

`<space>p` works normally, and `ctrl-shift-v` not.

**Comment by pascalkuthe** [comment]
This should be fixed on master by #8703

**Comment by Luv-Ray** [comment]
Does this mean I just need to wait for a patch and close the issue?

**Comment by pascalkuthe** [comment]
you can just use the master branch it's pretty stable

**Comment by Luv-Ray** [comment]
Now I'm using the master branch
```
$ git describe
23.10-39-g6ab774da
$ hx -V
helix 23.10 (6ab774da)
```
But the problem still exists, `ctrl-shift-v` can't paste text yanked by `<space>Y`.

**Comment by the-mikedavis** [comment]
This is probably a problem with the clipboard provider instead. Are you running X11 or Wayland? Can you copy/paste with `xclip` outside of Helix?

**Comment by Luv-Ray** [comment]
I'm using Wayland.
After running `echo "test" | xclip -selection clipboard`, I can paste "test" in browser, but can't paste "test" in Konsole.
Maybe the cause of the problem is Konsole?

**Comment by the-mikedavis** [comment]
If you're using Wayland then you will need `wl-clipboard` (`wl-copy` & `wl-paste`) rather than xclip - xclip is only for X11 as far as I know

**Comment by Luv-Ray** [comment]
It works good in `wl-clipboard`, thanks!
